# Generated by Django 5.2.8 on 2025-12-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FimLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('path', models.TextField()),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('process', models.CharField(blank=True, max_length=255, null=True)),
                ('full_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_fimlog_timesta_235070_idx'), models.Index(fields=['severity'], name='api_fimlog_severit_a12199_idx')],
            },
        ),
        migrations.CreateModel(
            name='WpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_wplog_timesta_940a5d_idx'), models.Index(fields=['category'], name='api_wplog_categor_a4e1d1_idx'), models.Index(fields=['action'], name='api_wplog_action_8e1800_idx')],
            },
        ),
    ]
