# Generated by Django 5.2.6 on 2025-12-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WpLog',
        ),
    ]
