# ============================================================================
# ⚠ DISCLAIMER
# This Ansible playbook is provided for portfolio and showcase purposes only.
# It represents a simplified and sanitized deployment workflow.
# Actual production configurations, credentials, and infrastructure details
# are managed securely and are not included in this repository.
# ============================================================================
---
- name: Production Deployment - Backend Django Application
  hosts: backend_servers
  become: yes
  vars:
    project_dir: '/home/runner/...' # change to your project directory
    git_repo: 'git@github.com:...' # change to your repository
    branch_name: 'main'
    venv_path: '{{ project_dir }}/venv'

  tasks:
    - name: 1. Fix Git 'Dubious Ownership' issue
      command: git config --global --add safe.directory {{ project_dir }}
      tags: git_config

    - name: 2. Pull latest source code from GitHub
      git:
        repo: '{{ git_repo }}'
        dest: '{{ project_dir }}'
        version: '{{ branch_name }}'
        force: yes
        accept_hostkey: yes
      register: git_output

    - name: 3. Install Python dependencies (Pip)
      pip:
        requirements: '{{ project_dir }}/requirements.txt'
        virtualenv: '{{ venv_path }}'
        virtualenv_command: python3 -m venv

    - name: 4. Apply Database Migrations
      command: '{{ venv_path }}/bin/python {{ project_dir }}/manage.py migrate'
      environment:
        DJANGO_ENV: production

    # --- CONTAINER ORCHESTRATION ---
    - name: 5. Restart Docker Services (Clean Slate)
      shell: |
        cd {{ project_dir }}

        # 1. Stop existing containers related to this project
        docker compose down --remove-orphans

        # 2. Prune unused Docker objects (Images, Networks, build cache)
        docker system prune -a -f

        # 3. Rebuild and Start containers
        docker compose up -d --build
      args:
        executable: /bin/bash
      register: docker_output

    - name: 6. Deployment Status
      debug:
        msg: '✅ Deployment Successful! Backend is live with the latest version.'
